# Generated by Django 3.2.3 on 2023-09-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230923_0607'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='following_restrict',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='author',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'author'), name='following_restrict'),
        ),
    ]
